### ISSUE TITLE
No xpcshell tests, so we can evolve this independently

### ISSUE THREAD

**Issue by lygstate** [mozilla-comm/jsmime#13]

**Comment by jcranmer** [comment]
Actually, the entire test suite functions as an xpcshell test suite if set up properly (note the xpcshell.ini, which lists the test that the browser-based chai variants use). It's hard to make this run as a xpcshell testsuite as is, but I have scripts that automate the task of importing a new version into the comm-central tree, and I use those to ensure that the built product passes all tests before accepting any new commits into the repository.

However, the use of browser-based tests using chai makes it rather easy to test most of this stuff independently of Thunderbird development. (Except for the sets of tests we have that make small changes to logic here pile on useless non-jsmime test changes).

**Comment by lygstate** [comment]
@jcranmer Now, I've convert the whole test suite to mocha + chai,
And removed all the old boilerplate codes for testing ( Cause they won't work anymore )

**Comment by jcranmer** [comment]
As mentioned in the pull request, this change is unacceptable.
